### ISSUE TITLE
ERROR Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.0:revision during the installation

### ISSUE THREAD

**Issue by fonzy209** [OpenConext-Attic/OpenConext-eduproxy#1]
During the installation process: the system shows an error: ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.0:revision (default) on project eduproxy: .git directory could not be found! Please specify a valid [dotGitDirectory] in your pom.xml  .

Any help to complete the install would be greatly appreciated

**Comment by thijskh** [comment]
Thanks for your request. This project is no longer in use and will be archived. You're free to use it, but we cannot help you currently to get it running.
